services:
  # nginx
  web:
      image: nginx:latest
      ports:
          - "80:80"
      volumes:
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  # php
  app:
      build: 
          dockerfile: ./Dockerfile
      volumes:
          # - ./app:/app
          - /var/www/html/vendor
          - ./app:/var/www/html
      environment:
         MYSQL_HOST: db
         MYSQL_USER: ${DB_USER}
         MYSQL_PASSWORD: ${DB_PASS}
         MYSQL_DATABASE: ${DB_NAME}

  # mysql
  db:
      image: mariadb
      volumes:
          - mysqldata:/var/lib/mysql
      restart: unless-stopped
      environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASS}
          MYSQL_USER: ${DB_USER}
          MYSQL_PASSWORD: ${DB_PASS}
          MYSQL_DATABASE: ${DB_NAME}
  
volumes:
  mysqldata: